version: '3.8'
services:
  maze_generator:
    build: ./maze_generator
    volumes:
      - ./maze_generator:/app
    command: python maze.py
  web_app:
    build: ./web_app
    ports:
      - "5000:5000"
    depends_on:
      - maze_generator
  database:
    build: ./database
    volumes:
      - ./database:/data
